### ISSUE TITLE
docs.ex throws an error

### ISSUE THREAD

**Issue by a-maze-d** [rrrene/inch_ex#99]
[This line](https://github.com/rrrene/inch_ex/blob/d37c3cd41ceda869696499569547d6f9a416751c/lib/inch_ex/docs.ex#L74):  throws an error, which can easily be fixed by changing the line to: `"location" => "#{inspect source}:#{inspect anno}"`

This is one of the reasons why I disabled inch_ex for now in [fledex](https://github.com/a-maze-d/fledex)

**Comment by a-maze-d** [comment]
Here the error I receive:
```
Generated fledex app

00:18:00.172 [error] Task #PID<0.251.0> started from #PID<0.99.0> terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[generated: true, location: 28]

    (elixir 1.15.7) lib/list.ex:1084: List.to_string/1
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:74: InchEx.Docs.cast_doc/3
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:48: InchEx.Docs.split_module_docs/6
    (inch_ex 2.1.0-rc.1) lib/inch_ex/cli/commands/suggest_command.ex:30: InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: #Function<2.130319517/0 in InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1>
    Args: []

00:18:00.172 [error] Task #PID<0.216.0> started from #PID<0.99.0> terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[generated: true, location: 17]

    (elixir 1.15.7) lib/list.ex:1084: List.to_string/1
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:74: InchEx.Docs.cast_doc/3
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:48: InchEx.Docs.split_module_docs/6
    (inch_ex 2.1.0-rc.1) lib/inch_ex/cli/commands/suggest_command.ex:30: InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: #Function<2.130319517/0 in InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1>
    Args: []
** (EXIT from #PID<0.99.0>) an exception was raised:
    ** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[generated: true, location: 28]

        (elixir 1.15.7) lib/list.ex:1084: List.to_string/1
        (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:74: InchEx.Docs.cast_doc/3
        (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:48: InchEx.Docs.split_module_docs/6
        (inch_ex 2.1.0-rc.1) lib/inch_ex/cli/commands/suggest_command.ex:30: InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1
        (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
        (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4


00:18:00.172 [error] Task #PID<0.218.0> started from #PID<0.99.0> terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[generated: true, location: 6]

    (elixir 1.15.7) lib/list.ex:1084: List.to_string/1
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:74: InchEx.Docs.cast_doc/3
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (inch_ex 2.1.0-rc.1) lib/inch_ex/docs.ex:48: InchEx.Docs.split_module_docs/6
    (inch_ex 2.1.0-rc.1) lib/inch_ex/cli/commands/suggest_command.ex:30: InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: #Function<2.130319517/0 in InchEx.CLI.Commands.SuggestCommand.fetch_and_evaluate_docs/1>
    Args: []

```

**Comment by tjchambers** [comment]
Unfortunately I have the same issue myself exactly...

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving/communicating this properly. 😥 

For what it is worth, this was fixed, but I realize that this might be way too late for your case 🙏

**Comment by a-maze-d** [comment]
Thanks
